
const CATEGORIES = [
  {
    name: "IMDb-Bewertungen",
    unit: "/10",
    items: [
      { label: "The Shawshank Redemption/Die Verurteilten", value: 9.3, url: "https://m.media-amazon.com/images/I/51A3zZer19L._SY300_SX300_QL70_ML2_.jpg" },
      { label: "The Godfather", value: 9.2, url: "https://m.media-amazon.com/images/I/61QWxqU+eFL._AC_UY218_.jpg" },
      { label: "The Dark Knight", value: 9.0, url: "https://m.media-amazon.com/images/I/41tqIUNiNjL._SY300_SX300_QL70_ML2_.jpg" },
      { label: "The Lord of the Rings: The Return of the King", value: 9.0, url: "https://m.media-amazon.com/images/I/91Nhaoj997L._AC_UY218_.jpg" },
      { label: "Pulp Fiction", value: 8.9, url: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Pulp_Fiction_%281994%29_poster.jpg/250px-Pulp_Fiction_%281994%29_poster.jpg" },
      { label: "Fight Club", value: 8.8, url: "https://m.media-amazon.com/images/I/510RJIrasdS._SY300_SX300_QL70_FMwebp_.jpg" },
      { label: "Inception", value: 8.8, url: "https://m.media-amazon.com/images/I/61CkZlbKdwL._SX385_.jpg" },
      { label: "Forrest Gump", value: 8.8, url: "https://m.media-amazon.com/images/I/61QCQ1HYAxL._AC_UY218_.jpg" },
      { label: "The Matrix", value: 8.7, url: "https://m.media-amazon.com/images/I/81ntkRLyBuL._AC_UY218_.jpg" },
      { label: "Goodfellas", value: 8.7, url: "https://m.media-amazon.com/images/I/91llG6OCC4L._AC_UY218_.jpg" },
      { label: "Interstellar", value: 8.7, url: "https://m.media-amazon.com/images/I/91QqHuKHfTL._AC_UY218_.jpg" },
      { label: "Se7en", value: 8.6, url: "https://m.media-amazon.com/images/I/71YICO7m9uL._AC_UY218_.jpg" },
      { label: "Gladiator", value: 8.5, url: "https://m.media-amazon.com/images/I/81v8WQ-eF-L._AC_UY218_.jpg" },
      { label: "The Departed", value: 8.5, url: "https://m.media-amazon.com/images/I/91BfKrFOpZL._AC_UY218_.jpg" },
      { label: "Whiplash", value: 8.5, url: "https://m.media-amazon.com/images/I/81eLULGWj+L._AC_UY218_.jpg" },
    ]
  },
  {
    name: "Instagram-Follower",
    unit: " Mio.",
    items: [
      { label: "Zendaya", value: 184, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Zendaya_-_2019_by_Glenn_Francis.jpg/250px-Zendaya_-_2019_by_Glenn_Francis.jpg" },
      { label: "Katy Perry", value: 200, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/KatyPerryWestminst111224_%2881_of_95%29_%2854206733094%29_%28cropped_2%29.jpg/250px-KatyPerryWestminst111224_%2881_of_95%29_%2854206733094%29_%28cropped_2%29.jpg" },
      { label: "Taylor Swift", value: 279, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png/250px-Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png" },
      { label: "Justin Bieber", value: 290, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Justin_Bieber_in_Rosemont%2C_Illinois_%282015%29_%28cropped%29.jpg/250px-Justin_Bieber_in_Rosemont%2C_Illinois_%282015%29_%28cropped%29.jpg" },
      { label: "Beyoncé", value: 320, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg/250px-Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg" },
      { label: "Khloé Kardashian", value: 300, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Khloe_Kardashian.jpg/250px-Khloe_Kardashian.jpg" },
      { label: "Nike", value: 304, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/250px-Logo_NIKE.svg.png" },
      { label: "Kim Kardashian", value: 360, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Kim_Kardashian_at_the_Met_Gala_in_2019_%28cropped%29.png/250px-Kim_Kardashian_at_the_Met_Gala_in_2019_%28cropped%29.png" },
      { label: "Ariana Grande", value: 380, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Ariana_Grande_promoting_Wicked_%282024%29.jpg/250px-Ariana_Grande_promoting_Wicked_%282024%29.jpg" },
      { label: "Dwayne Johnson", value: 390, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Dwayne_%22The_Rock%22_Johnson_Visits_the_Pentagon_%2841%29_%28cropped%29.jpg/250px-Dwayne_%22The_Rock%22_Johnson_Visits_the_Pentagon_%2841%29_%28cropped%29.jpg" },
      { label: "Kylie Jenner", value: 391, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Kylie_Jenner1_%28cropped%29.png/250px-Kylie_Jenner1_%28cropped%29.png" },
      { label: "Selena Gomez", value: 415, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_3_%28Cropped%29.jpg/250px-Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_3_%28Cropped%29.jpg" },
      { label: "Lionel Messi", value: 511, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg/250px-Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg" },
      { label: "Cristiano Ronaldo", value: 670, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_%28cropped%29.jpg/250px-Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_%28cropped%29.jpg" },
      { label: "Instagram", value: 700, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/250px-Instagram_logo_2022.svg.png" },
    ]
  },
  {
    name: "Kino-Einspielergebnis aller Zeiten",
    unit: " Mrd. $",
    items: [
      { label: "Jurassic Park", value: 1.03, url: "https://m.media-amazon.com/images/I/71jkDNeS4HL._AC_UY218_.jpg" },
      { label: "Deadpool & Wolverine", value: 1.34, url: "https://m.media-amazon.com/images/I/918g+-322uL._AC_UY218_.jpg" },
      { label: "Black Panther", value: 1.35, url: "https://m.media-amazon.com/images/I/A1GMi3PF9kL._AC_UY218_.jpg" },
      { label: "Barbie", value: 1.45, url: "https://m.media-amazon.com/images/I/71KOCxBjt2L._AC_UY218_.jpg" },
      { label: "Frozen II", value: 1.45, url: "https://m.media-amazon.com/images/I/A17LkHMuXrL._AC_UY218_.jpg" },
      { label: "Fast & Furious 7", value: 1.52, url: "https://m.media-amazon.com/images/I/817WhlSZVoL._AC_UY218_.jpg" },
      { label: "The Lion King", value: 1.66, url: "https://m.media-amazon.com/images/I/81Jpnbc3grL._AC_UY218_.jpg" },
      { label: "Jurassic World", value: 1.67, url: "https://m.media-amazon.com/images/I/71c78c3PA7L._AC_UY218_.jpg" },
      { label: "Spider-Man: No Way Home", value: 1.92, url: "https://m.media-amazon.com/images/I/91JJOEMLRRL._AC_UY218_.jpg" },
      { label: "Avengers: Infinity War", value: 2.05, url: "https://m.media-amazon.com/images/I/A1aHRPvn5JL._AC_UY218_.jpg" },
      { label: "Star Wars: The Force Awakens", value: 2.07, url: "https://m.media-amazon.com/images/I/919VmQGMCDL._AC_UY218_.jpg" },
      { label: "Titanic", value: 2.19, url: "https://m.media-amazon.com/images/I/81XmODGX7LL._AC_UY218_.jpg" },
      { label: "Avatar: The Way of Water", value: 2.34, url: "https://m.media-amazon.com/images/I/81iDpcE0tlL._AC_UY218_.jpg" },
      { label: "Avengers: Endgame", value: 2.80, url: "https://m.media-amazon.com/images/I/A1aHRPvn5JL._AC_UY218_.jpg" },
      { label: "Avatar", value: 2.92, url: "https://m.media-amazon.com/images/I/81uTpj+VGuL._AC_UY218_.jpg" },
    ]
  },
  {
    name: "Meistverkaufte Videospiele aller Zeiten",
    unit: " Mio.",
    items: [
      { label: "Grand Theft Auto: San Andreas", value: 27.5, url: "https://m.media-amazon.com/images/I/616ZeVGlFGL._AC_UY218_.jpg" },
      { label: "Super Mario Odyssey", value: 28, url: "https://m.media-amazon.com/images/I/61sv4VFKgJL._AC_UY218_.jpg" },
      { label: "Call of Duty: Modern Warfare 3", value: 30, url: "https://m.media-amazon.com/images/I/81jV82s67UL._AC_UY218_.jpg" },
      { label: "The Legend of Zelda: Breath of the Wild", value: 32, url: "https://m.media-amazon.com/images/I/81lsqTe-YiL._AC_UY218_.jpg" },
      { label: "Pokémon Rot/Blau", value: 31, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Pok%C3%A9mon_RB_logo.png/250px-Pok%C3%A9mon_RB_logo.png" },
      { label: "Terraria", value: 44, url: "https://m.media-amazon.com/images/I/6158RQK8LEL._AC_UY218_.jpg" },
      { label: "Animal Crossing: New Horizons", value: 45, url: "https://m.media-amazon.com/images/I/81xShs+ZnaL._AC_UY218_.jpg" },
      { label: "Overwatch", value: 50, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Overwatch4.svg/330px-Overwatch4.svg.png" },
      { label: "Mario Kart 8", value: 60, url: "https://upload.wikimedia.org/wikipedia/de/thumb/d/df/Mario_Kart_8.jpg/330px-Mario_Kart_8.jpg" },
      { label: "Red Dead Redemption 2", value: 65, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Red_Dead_Redemption_2_Logo.png/330px-Red_Dead_Redemption_2_Logo.png" },
      { label: "PUBG", value: 75, url: "https://wstatic-prod.pubg.com/web/live/main_156194a/img/1337804.webp" },
      { label: "Wii Sports", value: 83, url: "https://upload.wikimedia.org/wikipedia/de/thumb/8/84/Logo_von_Wii_Sports.svg/330px-Logo_von_Wii_Sports.svg.png" },
      { label: "GTA V", value: 205, url: "https://upload.wikimedia.org/wikipedia/de/thumb/7/74/GTA5-logo-o.svg/330px-GTA5-logo-o.svg.png" },
      { label: "Minecraft", value: 300, url: "https://upload.wikimedia.org/wikipedia/de/thumb/5/57/Minecraft_logo-SVG.svg/330px-Minecraft_logo-SVG.svg.png" },
      { label: "Tetris", value: 520, url: "https://upload.wikimedia.org/wikipedia/de/thumb/d/d5/TetrisGB.png/250px-TetrisGB.png" },
    ]
  },
  {
    name: "Metacritic-Bewertungen (Spiele)",
    unit: "/100",
    items: [
      { label: "Cyberpunk 2077", value: 86, url: "https://m.media-amazon.com/images/I/71n7miyPH5L._AC_UY218_.jpg" },
      { label: "Final Fantasy VII Remake", value: 87, url: "https://m.media-amazon.com/images/I/81KzGGGXAHL._AC_UY218_.jpg" },
      { label: "Resident Evil 4 (2023)", value: 88, url: "https://m.media-amazon.com/images/I/610futkds1L._AC_UY218_.jpg" },
      { label: "The Witcher 3", value: 93, url: "https://m.media-amazon.com/images/I/71mwMvt224L._AC_UY218_.jpg" },
      { label: "God of War (2018)", value: 94, url: "https://m.media-amazon.com/images/I/81Uml+O4HkL._AC_UY218_.jpg" },
      { label: "Portal 2", value: 95, url: "https://m.media-amazon.com/images/I/81s49gyeErL._AC_UY218_.jpg" },
      { label: "The Last of Us", value: 95, url: "https://m.media-amazon.com/images/I/81a0Cp9TB4L._AC_UY218_.jpg" },
      { label: "Half-Life 2", value: 96, url: "https://m.media-amazon.com/images/I/A1Lu3OslEUL._AC_UY218_.jpg" },
      { label: "BioShock", value: 96, url: "https://m.media-amazon.com/images/I/81xDlbhj7uL._AC_UY218_.jpg" },
      { label: "Elden Ring", value: 96, url: "https://m.media-amazon.com/images/I/81jxlBFH5xL._AC_UY218_.jpg" },
      { label: "Grand Theft Auto V", value: 97, url: "https://m.media-amazon.com/images/I/816nYZmor1L._AC_UY218_.jpg" },
      { label: "Red Dead Redemption 2", value: 97, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Red_Dead_Redemption_2_Logo.png/330px-Red_Dead_Redemption_2_Logo.png" },
      { label: "Super Mario Odyssey", value: 97, url: "https://m.media-amazon.com/images/I/61sv4VFKgJL._AC_UY218_.jpg" },
      { label: "Super Mario Galaxy", value: 97, url: "https://m.media-amazon.com/images/I/91ToBxYo8mL._AC_UY218_.jpg" },
      { label: "The Legend of Zelda: Ocarina of Time", value: 99, url: "https://m.media-amazon.com/images/I/71E61j8yKRL._AC_UY218_.jpg" },
    ]
  },
  {
    name: "Anime — MyAnimeList-Bewertungen",
    unit: "/10",
    items: [
      { label: "Sword Art Online", value: 7.2, url: "https://m.media-amazon.com/images/I/81xrAw9CfkL._AC_UY218_.jpg" },
      { label: "Tokyo Ghoul", value: 7.8, url: "https://m.media-amazon.com/images/I/71ofmLT92PL._AC_UY218_.jpg" },
      { label: "My Hero Academia", value: 7.9, url: "https://m.media-amazon.com/images/I/71Br4+9MqbL._AC_UY218_.jpg" },
      { label: "Naruto", value: 8.0, url: "https://m.media-amazon.com/images/I/81qJv4dQ8fL._AC_UY218_.jpg" },
      { label: "The Ancient Magus' Bride", value: 8.2, url: "https://m.media-amazon.com/images/I/81yiz0BHoDL._AC_UY218_.jpg" },
      { label: "Neon Genesis Evangelion", value: 8.4, url: "https://m.media-amazon.com/images/I/81-TgzKIslL._AC_UY218_.jpg" },
      { label: "Demon Slayer", value: 8.5, url: "https://m.media-amazon.com/images/I/916mTVw0teL._AC_UY218_.jpg" },
      { label: "Death Note", value: 8.6, url: "https://m.media-amazon.com/images/I/81qiVZuENZL._AC_UY218_.jpg" },
      { label: "Nana", value: 8.7, url: "https://m.media-amazon.com/images/I/818q-eBlxML._AC_UY218_.jpg" },
      { label: "Code Geass", value: 8.7, url: "https://m.media-amazon.com/images/I/81WeyQcCv1L._AC_UY218_.jpg" },
      { label: "Cowboy Bebop", value: 8.8, url: "https://m.media-amazon.com/images/I/81PwS-d2DqL._AC_UY218_.jpg" },
      { label: "Jujutsu Kaisen", value: 8.8, url: "https://m.media-amazon.com/images/I/91wBniChnvL._AC_UY218_.jpg" },
      { label: "Hunter x Hunter (2011)", value: 9.0, url: "https://m.media-amazon.com/images/I/81zmXm+JF3L._AC_UY218_.jpg" },
      { label: "Steins;Gate", value: 9.1, url: "https://m.media-amazon.com/images/I/81EfptVpSZL._AC_UY218_.jpg" },
      { label: "Fullmetal Alchemist: Brotherhood", value: 9.2, url: "https://m.media-amazon.com/images/I/81jzczfO3WL._AC_UY218_.jpg" },
    ]
  },
  {
    name: "Meistverkaufte Manga-Reihen aller Zeiten",
    unit: " Mio. Bände",
    items: [
      { label: "One Punch Man", value: 30, url: "https://m.media-amazon.com/images/I/81qkHgX28EL._AC_UY218_.jpg" },
      { label: "Berserk", value: 60, url: "https://m.media-amazon.com/images/I/71LaDNbnY8L._AC_UY218_.jpg" },
      { label: "Fairy Tail", value: 72, url: "https://m.media-amazon.com/images/I/812RBr4WsZL._AC_UY218_.jpg" },
      { label: "My Hero Academia", value: 85, url: "https://m.media-amazon.com/images/I/71Br4+9MqbL._AC_UY218_.jpg" },
      { label: "Fist of the North Star", value: 100, url: "https://m.media-amazon.com/images/I/91NQBeRSnrL._AC_UY218_.jpg" },
      { label: "Attack on Titan", value: 145, url: "https://m.media-amazon.com/images/I/81ANM5zMDUL._AC_UY218_.jpg" },
      { label: "JoJo's Bizarre Adventure", value: 120, url: "https://m.media-amazon.com/images/I/81BMT+PjP5L._AC_UY218_.jpg" },
      { label: "Bleach", value: 130, url: "https://m.media-amazon.com/images/I/811jOwgD5gL._AC_UY218_.jpg" },
      { label: "Kochikame", value: 156, url: "https://m.media-amazon.com/images/I/61HWIIz7C1L._AC_UL320_.jpg" },
      { label: "Slam Dunk", value: 170, url: "https://m.media-amazon.com/images/I/711Ve-uC2TL._AC_UY218_.jpg" },
      { label: "Demon Slayer", value: 220, url: "https://m.media-amazon.com/images/I/916mTVw0teL._AC_UY218_.jpg" },
      { label: "Detective Conan", value: 245, url: "https://m.media-amazon.com/images/I/71s44HuBYPL._AC_UY218_.jpg" },
      { label: "Naruto", value: 253, url: "https://m.media-amazon.com/images/I/81qJv4dQ8fL._AC_UY218_.jpg" },
      { label: "Dragon Ball", value: 260, url: "https://m.media-amazon.com/images/I/81EvrdX0RXL._AC_UY218_.jpg" },
      { label: "One Piece", value: 516, url: "https://m.media-amazon.com/images/I/815pCrOs9qL._AC_UY218_.jpg" },
    ]
  },
  {
    name: "Olympische Spiele — meiste Goldmedaillen",
    unit: " Gold",
    items: [
      { label: "Kanada", value: 77, url: "https://flagcdn.com/w320/ca.png" },
      { label: "Kuba", value: 78, url: "https://flagcdn.com/w320/cu.png" },
      { label: "Rumänien", value: 88, url: "https://flagcdn.com/w320/ro.png" },
      { label: "Niederlande", value: 95, url: "https://flagcdn.com/w320/nl.png" },
      { label: "Südkorea", value: 96, url: "https://flagcdn.com/w320/kr.png" },
      { label: "Schweden", value: 147, url: "https://flagcdn.com/w320/se.png" },
      { label: "Japan", value: 169, url: "https://flagcdn.com/w320/jp.png" },
      { label: "Australien", value: 164, url: "https://flagcdn.com/w320/au.png" },
      { label: "Ungarn", value: 175, url: "https://flagcdn.com/w320/hu.png" },
      { label: "Italien", value: 226, url: "https://flagcdn.com/w320/it.png" },
      { label: "Frankreich", value: 233, url: "https://flagcdn.com/w320/fr.png" },
      { label: "Deutschland", value: 252, url: "https://flagcdn.com/w320/de.png" },
      { label: "Grossbritannien", value: 296, url: "https://flagcdn.com/w320/gb.png" },
      { label: "China", value: 303, url: "https://flagcdn.com/w320/cn.png" },
      { label: "USA", value: 1061, url: "https://flagcdn.com/w320/us.png" },
    ]
  },
  {
    name: "Meiste internationale Touristen (Stand 2025)",
    unit: " Mio. / Jahr",
    items: [
      { label: "Niederlande", value: 20, url: "https://flagcdn.com/w320/nl.png" },
      { label: "Portugal", value: 21, url: "https://flagcdn.com/w320/pt.png" },
      { label: "Malaysia", value: 22, url: "https://flagcdn.com/w320/my.png" },
      { label: "Japan", value: 25, url: "https://flagcdn.com/w320/jp.png" },
      { label: "Thailand", value: 28, url: "https://flagcdn.com/w320/th.png" },
      { label: "Österreich", value: 31, url: "https://flagcdn.com/w320/at.png" },
      { label: "Griechenland", value: 33, url: "https://flagcdn.com/w320/gr.png" },
      { label: "Deutschland", value: 35, url: "https://flagcdn.com/w320/de.png" },
      { label: "Grossbritannien", value: 38, url: "https://flagcdn.com/w320/gb.png" },
      { label: "Mexiko", value: 42, url: "https://flagcdn.com/w320/mx.png" },
      { label: "Türkei", value: 55, url: "https://flagcdn.com/w320/tr.png" },
      { label: "Italien", value: 57, url: "https://flagcdn.com/w320/it.png" },
      { label: "USA", value: 66, url: "https://flagcdn.com/w320/us.png" },
      { label: "Spanien", value: 85, url: "https://flagcdn.com/w320/es.png" },
      { label: "Frankreich", value: 100, url: "https://flagcdn.com/w320/fr.png" },
    ]
  },
  {
    name: "Wann sind diese Filme erschienen",
    unit: "",
    items: [
      { label: "Casablanca", value: 1942, url: "https://m.media-amazon.com/images/I/91oWq-RSI6L._AC_UY218_.jpg" },
      { label: "Jaws", value: 1975, url: "https://m.media-amazon.com/images/I/81trJhYm5NL._AC_UY218_.jpg" },
      { label: "Star Wars", value: 1977, url: "https://m.media-amazon.com/images/I/91znxHmQNhL._AC_UY218_.jpg" },
      { label: "E.T.", value: 1982, url: "https://m.media-amazon.com/images/I/71OD6TfOaiL._AC_UY218_.jpg" },
      { label: "Jurassic Park", value: 1993, url: "https://m.media-amazon.com/images/I/71jkDNeS4HL._AC_UY218_.jpg" },
      { label: "The Lion King", value: 1994, url: "https://m.media-amazon.com/images/I/81Jpnbc3grL._AC_UY218_.jpg" },
      { label: "Titanic", value: 1997, url: "https://m.media-amazon.com/images/I/81XmODGX7LL._AC_UY218_.jpg" },
      { label: "The Matrix", value: 1999, url: "https://m.media-amazon.com/images/I/81YGjCdK1DL._AC_UY218_.jpg" },
      { label: "The Lord of the Rings: The Fellowship of the Ring", value: 2001, url: "https://m.media-amazon.com/images/I/91DGwmaFdxL._AC_UY218_.jpg" },
      { label: "Avatar", value: 2009, url: "https://m.media-amazon.com/images/I/91XXks9tlfL._AC_UY218_.jpg" },
      { label: "Inception", value: 2010, url: "https://m.media-amazon.com/images/I/81k9bJA4MuL._AC_UY218_.jpg" },
      { label: "The Avengers", value: 2012, url: "https://m.media-amazon.com/images/I/A1n9lWtmBNL._AC_UY218_.jpg" },
      { label: "Frozen", value: 2013, url: "https://m.media-amazon.com/images/I/91B3FM9YaNL._AC_UY218_.jpg" },
      { label: "Interstellar", value: 2014, url: "https://m.media-amazon.com/images/I/712I5GOGprL._AC_UY218_.jpg" },
      { label: "Barbie", value: 2023, url: "https://m.media-amazon.com/images/I/71KOCxBjt2L._AC_UL320_.jpg" },
    ]
  },
  {
    name: "Teuerste Spiele-Entwicklungsbudgets",
    unit: " Mio. $",
    items: [
      { label: "The Witcher 3", value: 81, url: "https://m.media-amazon.com/images/I/71mwMvt224L._AC_UY218_.jpg" },
      { label: "Halo 2", value: 120, url: "https://i.pinimg.com/1200x/77/30/38/773038be5c27b104c6b3065f73ffbbc1.jpg" },
      { label: "Final Fantasy VII", value: 140, url: "https://m.media-amazon.com/images/I/81KzGGGXAHL._AC_UY218_.jpg" },
      { label: "Hogwarts Legacy", value: 150, url: "https://i.pinimg.com/1200x/af/bf/cf/afbfcfcaf49486a63eafbd6e845beccf.jpg" },
      { label: "Horizon Forbidden West", value: 212, url: "https://i.pinimg.com/736x/db/be/da/dbbeda64fcd2c51283841b5e17301010.jpg" },
      { label: "The Last of Us Part II", value: 220, url: "https://m.media-amazon.com/images/I/81a0Cp9TB4L._AC_UY218_.jpg" },
      { label: "Call of Duty: Modern Warfare 2", value: 250, url: "https://m.media-amazon.com/images/I/81jV82s67UL._AC_UY218_.jpg" },
      { label: "Grand Theft Auto V", value: 265, url: "https://upload.wikimedia.org/wikipedia/de/thumb/7/74/GTA5-logo-o.svg/330px-GTA5-logo-o.svg.png" },
      { label: "Spider-Man 2", value: 300, url: "https://i.pinimg.com/1200x/39/0a/c7/390ac77b3a7685e8af75467105bb90f4.jpg" },
      { label: "Cyberpunk 2077", value: 316, url: "https://m.media-amazon.com/images/I/71n7miyPH5L._AC_UY218_.jpg" },
      { label: "Starfield", value: 400, url: "https://i.pinimg.com/736x/93/63/9b/93639ba290915e24619d7b11c0541ea6.jpg" },
      { label: "Red Dead Redemption 2", value: 540, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Red_Dead_Redemption_2_Logo.png/330px-Red_Dead_Redemption_2_Logo.png" },
      { label: "Genshin Impact", value: 900, url: "https://i.pinimg.com/736x/ab/e0/19/abe019d59a86a88b52a6257ea454269e.jpg" },
      { label: "Star Citizen", value: 1100, url: "https://i.pinimg.com/736x/49/4d/54/494d542194d29e23c0063381d93b5ad6.jpg" },
      { label: "Grand Theft Auto VI", value: 2000, url: "https://i.pinimg.com/736x/f5/d8/37/f5d837f70cf9a502245348efb3d48773.jpg" },
    ]
  },
];
