const SITUATIONEN = [
  "Du kommst um 4 Uhr morgens nach Hause. Deine Mutter steht in der Küche.",
  "Du hast das Meeting verpasst, in dem du präsentieren solltest.",
  "Der Kuchen deiner Grossmutter ist leer, bevor die Gäste kommen.",
  "Du hast dem Chef aus Versehen eine Sprachnachricht geschickt.",
  "Die Polizei hält dich an. Auf dem Rücksitz liegen zwölf Gartenzwerge.",
  "Du hast den Geburtstag deiner besten Freundin vergessen.",
  "Dein Nachbar findet seinen Rasenmäher in deinem Keller.",
  "Du wachst in einem fremden Bus in einer fremden Stadt auf.",
  "Die Prüfungsaufsicht sieht Notizen auf deinem Handgelenk.",
  "Du kommst mit einem Auge zugeklebt zum Bewerbungsgespräch.",
  "Der Vermieter steht vor der Tür. Im Flur steht ein Pony.",
  "Du hast alle Snacks aufgegessen, die für die Party gedacht waren.",
  "Dein Trainer fragt, warum du drei Wochen nicht im Training warst.",
  "Du sitzt in der falschen Vorlesung und wirst aufgerufen.",
  "Die Rechnung im Restaurant kommt. Dein Portemonnaie ist leer.",
  "Du hast das Auto deines Vaters mit leerem Tank zurückgebracht.",
  "Auf deinem Bildschirm läuft im Videocall etwas sehr Falsches.",
  "Du wirst dabei erwischt, wie du den Kühlschrank im Büro leerräumst.",
  "Dein Hund hat die Hausaufgaben deiner Schwester gefressen.",
  "Du kommst zwei Stunden zu spät zur eigenen Überraschungsparty.",
  "Der Zugbegleiter fragt nach deinem Ticket. Du hast keins.",
  "Dein Kumpel fragt, wo die 200 Franken sind, die er dir geliehen hat.",
  "Du hast die Pflanze deiner Mitbewohnerin komplett eingehen lassen.",
  "Im Fitnessstudio bricht das Gerät, an dem du sitzt.",
  "Du hast versehentlich die Gruppennachricht an die falsche Gruppe geschickt.",
  "Deine Freundin findet ein zweites Handy in deiner Jacke.",
  "Du stehst um Mitternacht im Supermarkt in Badeschlappen und Anzugjacke.",
  "Der Lehrer fragt, warum dein Aufsatz wortwörtlich dem deines Sitznachbarn gleicht.",
  "Du hast das Hochzeitsgeschenk im Zug liegen gelassen.",
  "Die Katze deiner Nachbarin sitzt seit drei Tagen in deiner Wohnung.",
  "Du wirst gefragt, warum du beim Videocall die Kamera nie anmachst.",
  "Am Flughafen fragt der Zoll, was in deinem Koffer klappert.",
  "Du hast den letzten Kaffee genommen und die Kanne nicht neu aufgesetzt.",
  "Dein Bruder fragt, wo sein Lieblingspullover geblieben ist.",
  "Du bist auf einem Foto zu sehen, wo du eigentlich krank sein solltest.",
  "Der Kellner bringt eine Rechnung über 340 Franken für Getränke.",
  "Du hast beim Umzug die Kiste mit dem Porzellan fallen lassen.",
  "Deine Mitbewohner fragen, warum die Waschmaschine nach Fisch riecht.",
  "Du hast im Gruppenprojekt nichts gemacht und wirst nach deinem Teil gefragt.",
  "Der Hausmeister fragt, warum der Feueralarm um 3 Uhr losging.",
  "Du kommst mit Grasflecken und einem Schuh nach Hause.",
  "Die Nachbarn beschweren sich über Karaoke um zwei Uhr nachts.",
  "Du hast das Passwort für den gemeinsamen Account geändert.",
  "Deine Tante fragt, warum du ihre Anrufe seit Monaten wegdrückst.",
  "Im Kino klingelt dein Handy während der leisesten Szene.",
  "Du hast versehentlich das Bild deines Chefs kommentiert.",
  "Der Paketbote fragt, warum du sieben Pakete am Tag bekommst.",
  "Du sitzt im Bewerbungsgespräch und dein Magen macht Geräusche.",
  "Deine Schwester findet ihr Tagebuch aufgeschlagen auf deinem Bett.",
  "Du hast beim Grillen das Fleisch aller Gäste verbrennen lassen.",
  "Der Zahnarzt fragt, wann du zuletzt Zahnseide benutzt hast.",
  "Du kommst zur Beerdigung in einem knallgelben Anzug.",
  "Dein Team fragt, warum der Server seit gestern offline ist.",
  "Du hast die Fernbedienung so versteckt, dass du sie selbst nicht findest.",
  "Die Kassiererin fragt, warum die Packung Kekse geöffnet ist.",
  "Du wirst gefragt, warum du auf der Hochzeit alleine getanzt hast.",
  "Dein Kollege fragt, warum sein Mittagessen im Kühlschrank fehlt.",
  "Du hast dich im Videocall vergessen stummzuschalten und geschimpft.",
  "Die Schulleitung fragt, warum ein Schaf im Klassenzimmer steht.",
  "Du kommst mit einer neuen Frisur nach Hause, die niemand erwartet hat.",
  "Beim Wandern verlierst du die Karte und behauptest, du kennst den Weg.",
  "Dein Chef fragt, warum du im Homeoffice nie erreichbar bist.",
  "Du wirst beim Klauen von Blumen aus dem Nachbargarten erwischt.",
  "Der Freund fragt, warum sein Spiel zerkratzt zurückkommt.",
  "Du sitzt im falschen Flugzeug und bemerkst es beim Start.",
  "Deine Mutter findet deinen Kontoauszug auf dem Küchentisch.",
  "Du hast das Netflix-Finale ohne deinen Partner geschaut.",
  "Der Vermieter fragt, warum ein Loch in der Wand ist.",
  "Du kommst zur Prüfung ohne Stift, Ausweis und Uhr.",
  "Dein Nachbar fragt, warum seine Post bei dir landet.",
  "Du hast die Playlist für die Party gemacht und alle gehen früh.",
  "Die Freundin fragt, warum du ihren Namen falsch geschrieben hast.",
  "Du wirst gefragt, warum du drei Wecker stellst und trotzdem verschläfst.",
  "Im Zoo fragt der Wärter, warum du hinter der Absperrung stehst.",
  "Du hast beim Kochen die Küche unter Wasser gesetzt.",
  "Dein Kumpel fragt, warum du seinen Geburtstag doppelt gefeiert hast.",
  "Die Bank fragt, wofür die Abhebung um 3 Uhr morgens war.",
  "Du kommst mit dem Fahrrad deines Nachbarn nach Hause.",
  "Der Trainer fragt, warum du im Spiel in die falsche Richtung gelaufen bist.",
  "Du hast das WLAN-Passwort an die halbe Nachbarschaft weitergegeben.",
  "Deine Eltern fragen, warum ein Tattoo auf deinem Arm ist.",
  "Du wirst gefragt, warum du beim Escape Room die Tür eingetreten hast.",
  "Der Kellner fragt, warum ihr das Besteck einpackt.",
  "Du hast beim Umzug das Sofa im Treppenhaus stecken lassen.",
  "Deine Mitbewohnerin fragt, warum ihr Shampoo halb leer ist.",
  "Du kommst zum Vorstellungsgespräch in der Jogginghose.",
  "Der Nachbar fragt, warum sein Auto anders parkt als gestern Abend.",
  "Du hast auf dem Konzert das Ticket verloren und stehst draussen.",
  "Deine Freunde fragen, warum du in den Ferien nie geantwortet hast.",
  "Du wirst dabei ertappt, wie du im Büro schläfst.",
  "Der Busfahrer fragt, warum du ohne Schuhe einsteigst.",
  "Du hast versehentlich das falsche Geschenk übergeben.",
  "Dein Team fragt, warum die Präsentation nur aus einer Folie besteht.",
  "Die Nachbarin fragt, warum ihr Gartenzaun umgefallen ist.",
  "Du kommst vom Einkaufen zurück ohne einen einzigen Artikel von der Liste.",
  "Der Dozent fragt, warum du seit Wochen nicht in der Vorlesung warst.",
  "Du hast die Grillkohle im Wohnzimmer angezündet.",
  "Dein Partner fragt, warum das Auto nach Pommes riecht.",
  "Du wirst gefragt, warum du die Party um 21 Uhr verlassen hast.",
  "Die Wirtin fragt, warum ein Stuhl fehlt.",
  "Du hast im Museum ein Absperrband gerissen."
];

window.SITUATIONEN = SITUATIONEN;
