
const WOERTER = [
  { kategorie: "Tier", wort: "Giraffe" },
  { kategorie: "Tier", wort: "Pinguin" },
  { kategorie: "Tier", wort: "Hai" },
  { kategorie: "Essen", wort: "Pizza" },
  { kategorie: "Essen", wort: "Sushi" },
  { kategorie: "Essen", wort: "Döner" },
  { kategorie: "Beruf", wort: "Feuerwehrmann" },
  { kategorie: "Beruf", wort: "Chirurg" },
  { kategorie: "Beruf", wort: "Pilot" },
  { kategorie: "Ort", wort: "Flughafen" },
  { kategorie: "Ort", wort: "Krankenhaus" },
  { kategorie: "Ort", wort: "Bibliothek" },
  { kategorie: "Gegenstand", wort: "Regenschirm" },
  { kategorie: "Gegenstand", wort: "Kühlschrank" },
  { kategorie: "Gegenstand", wort: "Wecker" },
  { kategorie: "Sportart", wort: "Volleyball" },
  { kategorie: "Sportart", wort: "Bogenschiessen" },
  { kategorie: "Sportart", wort: "Schwimmen" },
  { kategorie: "Filmgenre", wort: "Horrorfilm" },
  { kategorie: "Filmgenre", wort: "Liebeskomödie" },
  { kategorie: "Jahreszeit", wort: "Herbst" },
  { kategorie: "Wetter", wort: "Gewitter" },
  { kategorie: "Fahrzeug", wort: "U-Boot" },
  { kategorie: "Fahrzeug", wort: "Heissluftballon" },
  { kategorie: "Getränk", wort: "Kaffee" },
  { kategorie: "Getränk", wort: "Limonade" },
  { kategorie: "Möbel", wort: "Hängematte" },
  { kategorie: "Naturphänomen", wort: "Vulkan" },
  { kategorie: "Naturphänomen", wort: "Regenbogen" },
  { kategorie: "Feiertag", wort: "Silvester" },
  { kategorie: "Musikinstrument", wort: "Akkordeon" },
  { kategorie: "Kleidung", wort: "Schneeanzug" },
  { kategorie: "Videospiel-Genre", wort: "Jump'n'Run" },
  { kategorie: "Gebäude", wort: "Leuchtturm" },
  { kategorie: "Werkzeug", wort: "Schraubenzieher" },
];
