
const BLUFF_FRAGEN = [
  { frage: "In einigen Schweizer Gemeinden ist es verboten, sonntags ___.", antwort: "die Wäsche im Freien aufzuhängen" },
  { frage: "In Japan gibt es einen Wettbewerb, bei dem Teilnehmer ___ so lange wie möglich machen.", antwort: "gar nichts" },
  { frage: "Eine Gruppe Flamingos nennt man ___.", antwort: "eine Flamboyance" },
  { frage: "Bevor es Radiergummis gab, benutzten Leute ___, um Bleistift zu entfernen.", antwort: "altbackenes Brot" },
  { frage: "Der Name «Nintendo» bedeutet übersetzt ungefähr ___.", antwort: "überlasse das Glück dem Himmel" },
  { frage: "Astronauten dürfen im All kein ___ essen, weil die Krümel gefährlich sind.", antwort: "normales Brot" },
  { frage: "Der teuerste Kaffee der Welt wird aus Bohnen gemacht, die vorher ___.", antwort: "von einer Schleichkatze verdaut wurden" },
  { frage: "Ein Blauwal-Herz ist ungefähr so gross wie ___.", antwort: "ein Kleinwagen" },
  { frage: "In Finnland gibt es eine Weltmeisterschaft im ___.", antwort: "Ehefrauentragen" },
  { frage: "Bananen sind botanisch gesehen eigentlich ___.", antwort: "Beeren" },
  { frage: "Ein Krake hat ___ Herzen.", antwort: "drei" },
  { frage: "Das lauteste Tier der Welt gemessen in Dezibel ist ___.", antwort: "der Pistolenkrebs" },
  { frage: "Honig kann nach tausenden Jahren noch ___.", antwort: "gegessen werden" },
  { frage: "Der Begriff «Bluetooth» kommt von ___.", antwort: "einem dänischen Wikingerkönig" },
  { frage: "In der Schweiz darf man Meerschweinchen nicht ___.", antwort: "einzeln halten" },
  { frage: "Die Wolken auf der Venus bestehen hauptsächlich aus ___.", antwort: "Schwefelsäure" },
  { frage: "Der grösste je gefundene Pilz ist ___.", antwort: "grösser als 900 Hektar" },
  { frage: "Kühe haben nachweislich ___.", antwort: "beste Freundinnen" },
  { frage: "Der Eiffelturm wird im Sommer bis zu ___ höher.", antwort: "15 Zentimeter" },
  { frage: "Ein Schnecke kann bis zu ___ am Stück schlafen.", antwort: "drei Jahre" },
  { frage: "Die erste Ware, die je über das Internet verkauft wurde, war ___.", antwort: "eine Tüte Marihuana" },
  { frage: "Wombat-Kot hat die Form ___.", antwort: "eines Würfels" },
  { frage: "In Schottland gibt es ein Gesetz, das ___ verbietet.", antwort: "einen Wal als Fund für sich zu behalten (gehört der Krone)" },
  { frage: "Der durchschnittliche Mensch verbringt etwa ___ seines Lebens auf der Toilette.", antwort: "drei Jahre" },
  { frage: "Ketchup wurde ursprünglich verkauft als ___.", antwort: "Medizin" },
  { frage: "In Südkorea gibt es Wettbewerbe, bei denen Teilnehmer ___.", antwort: "möglichst lange nichts tun" },
  { frage: "Eine Gruppe Eulen nennt man ___.", antwort: "ein Parlament" },
  { frage: "Der längste je gemessene Blitz war ___ lang.", antwort: "768 Kilometer" },
  { frage: "Vor der Erfindung des Weckers gab es Menschen, die beruflich ___.", antwort: "an Fenster klopften" },
  { frage: "Der Name «Wikipedia» kommt vom hawaiianischen Wort für ___.", antwort: "schnell" },
  { frage: "Auf dem Mars würde ein Feuerzeug ___.", antwort: "nicht brennen" },
  { frage: "Der erste Gegenstand, der je online verkauft wurde, war ___.", antwort: "eine CD von Sting" },
  { frage: "Ein Kolibri muss täglich ___, sonst verhungert er.", antwort: "das Doppelte seines Gewichts fressen" },
  { frage: "In Norwegen wurde ein Pinguin offiziell ___.", antwort: "zum Ritter geschlagen" },
  { frage: "Erdbeeren sind botanisch gesehen keine Beeren, sondern ___.", antwort: "Sammelnussfrüchte" },
  { frage: "Ein Wombat produziert Kot in der Form von ___.", antwort: "Würfeln" },
  { frage: "Das älteste noch arbeitende Unternehmen der Welt baut seit 578 ___.", antwort: "Tempel" },
  { frage: "Schnurrbärte waren in der britischen Armee bis 1916 ___.", antwort: "Pflicht" },
  { frage: "Der Buchstabe, der in keinem Namen eines US-Bundesstaates vorkommt, ist ___.", antwort: "Q" },
  { frage: "Ein Faultier braucht bis zu ___, um eine Mahlzeit zu verdauen.", antwort: "einen Monat" },
  { frage: "In Schweden gibt es eine Hotline, bei der man ___.", antwort: "mit einem zufälligen Schweden spricht" },
  { frage: "Der Klang eines knackenden Fingerknöchels entsteht durch ___.", antwort: "platzende Gasblasen" },
  { frage: "Venusflytrap-Pflanzen zählen ___, bevor sie zuschnappen.", antwort: "die Berührungen" },
  { frage: "Die Krawatte stammt ursprünglich von ___.", antwort: "kroatischen Söldnern" },
  { frage: "Ein durchschnittlicher Mensch verbringt etwa ___ seines Lebens an roten Ampeln.", antwort: "sechs Monate" },
  { frage: "Delfine geben sich gegenseitig ___.", antwort: "Namen" },
  { frage: "Das Wort «Ketchup» bezeichnete ursprünglich ___.", antwort: "eine Fischsauce" },
  { frage: "In Island ist es verboten, Hunde ___.", antwort: "in Reykjavík zu halten" },
  { frage: "Ein Jahr auf dem Merkur dauert ___ Merkurtage.", antwort: "weniger als zwei" },
  { frage: "Die ersten Fussbälle wurden aus ___ hergestellt.", antwort: "Schweinsblasen" },
  { frage: "Bienen können ___ erkennen.", antwort: "menschliche Gesichter" },
  { frage: "Der offizielle Beruf «Käseroller» existiert in ___.", antwort: "England" },
  { frage: "Ein Blitz erhitzt die Luft auf etwa ___.", antwort: "30000 Grad" },
  { frage: "Kängurus können nicht ___.", antwort: "rückwärts gehen" },
  { frage: "Das Wort «Roboter» stammt aus dem Tschechischen und bedeutet ___.", antwort: "Fronarbeit" },
  { frage: "In Japan gibt es Automaten, die ___ verkaufen.", antwort: "frische Eier" },
  { frage: "Die Farbe Orange wurde nach ___ benannt.", antwort: "der Frucht" },
  { frage: "Ein Oktopus kann ___, um sich zu tarnen.", antwort: "seine Hautstruktur ändern" },
  { frage: "Der grösste Diamant im Universum ist ___.", antwort: "ein ganzer Stern" },
  { frage: "In der Antarktis gibt es offiziell ___.", antwort: "einen Geldautomaten" },
  { frage: "Motten fühlen sich zu Licht hingezogen, weil sie ___.", antwort: "sich am Mond orientieren" },
  { frage: "Ein Schneckenzahn-Vergleich zeigt: Schnecken haben bis zu ___ Zähne.", antwort: "25000" },
  { frage: "Die durchschnittliche Wolke wiegt etwa ___.", antwort: "500 Tonnen" },
  { frage: "Bevor Toilettenpapier üblich wurde, nutzten Römer ___.", antwort: "einen Schwamm am Stock" },
  { frage: "Ein Kuhfladen benötigt ___, um vollständig zu trocknen.", antwort: "etwa zwei Wochen" },
  { frage: "Der erste Computerbug war ___.", antwort: "eine echte Motte" },
  { frage: "Haie existieren länger als ___.", antwort: "Bäume" },
  { frage: "Auf Saturn und Jupiter regnet es vermutlich ___.", antwort: "Diamanten" },
  { frage: "Der menschliche Magen erneuert seine Schleimhaut alle ___.", antwort: "drei bis vier Tage" },
  { frage: "In Bhutan misst die Regierung offiziell ___.", antwort: "das Bruttonationalglück" },
  { frage: "Eine Giraffe hat gleich viele Halswirbel wie ___.", antwort: "ein Mensch" },
  { frage: "Der teuerste Gewürzstoff der Welt ist ___.", antwort: "Safran" },
  { frage: "Pandas verbringen täglich bis zu ___ mit Fressen.", antwort: "14 Stunden" },
  { frage: "Das menschliche Auge kann etwa ___ Farbnuancen unterscheiden.", antwort: "10 Millionen" },
  { frage: "In Finnland gibt es eine Meisterschaft im ___.", antwort: "Handyweitwurf" }
];
