
const RAETSEL = [
  { emojis: ["🍄", "🏰", "🐢", "🇮🇹"], antwort: "Super Mario" },
  { emojis: ["🗡️", "🐉", "🛡️", "🐺"], antwort: "The Witcher" },
  { emojis: ["🔫", "💎", "🚗", "🌆"], antwort: "Grand Theft Auto" },
  { emojis: ["⛏️", "🟩", "🐷", "🧟"], antwort: "Minecraft" },
  { emojis: ["🎯", "🪂", "🔫", "🏝️"], antwort: "Fortnite" },
  { emojis: ["🐦", "🟢", "🐷", "💥"], antwort: "Angry Birds" },
  { emojis: ["🍌", "🦍", "🛢️", "🪜"], antwort: "Donkey Kong" },
  { emojis: ["👻", "🟡", "🔵", "🍒"], antwort: "Pac-Man" },
  { emojis: ["🦔", "💍", "💨", "🔵"], antwort: "Sonic" },
  { emojis: ["⚔️", "🛡️", "🧝", "🏔️"], antwort: "The Legend of Zelda" },
  { emojis: ["🔴", "⚪", "⚡", "🎒"], antwort: "Pokémon" },
  { emojis: ["🎸", "🥁", "🎤", "🌟"], antwort: "Guitar Hero" },
  { emojis: ["🚗", "🍄", "🐢", "🏁"], antwort: "Mario Kart" },
  { emojis: ["🟦", "🧱", "🕹️", "🧩"], antwort: "Tetris" },
  { emojis: ["🔪", "🚪", "😱", "👤"], antwort: "Among Us" },
  { emojis: ["🐤", "💛", "🎮", "🌾"], antwort: "Stardew Valley" },
  { emojis: ["🌌", "🚀", "👾", "🔫"], antwort: "Halo" },
  { emojis: ["🧟", "🌆", "💊", "🔦"], antwort: "Resident Evil" },
  { emojis: ["🐺", "🌙", "🏹", "❄️"], antwort: "God of War" },
  { emojis: ["🟩", "👻", "🍄", "🔦"], antwort: "Luigi's Mansion" },
  { emojis: ["🎻", "🚢", "🧊", "🎼"], antwort: "Interstellar" },
  { emojis: ["🐝", "🎬", "🍯", "🟡"], antwort: "Bee Movie" },
  { emojis: ["🦕", "☄️", "👣", "🌋"], antwort: "In einem Land vor unserer Zeit" },
  { emojis: ["🧠", "😀", "😢", "😡"], antwort: "Alles steht Kopf" },
  { emojis: ["💊", "🕶️", "🐇", "💻"], antwort: "Matrix" },
  { emojis: ["👗", "👠", "💃", "🎬"], antwort: "Der Teufel trägt Prada" },
  { emojis: ["💍", "🌋", "🧝", "🗡️"], antwort: "Herr der Ringe" },
  { emojis: ["❄️", "👑", "⛄", "🎶"], antwort: "Die Eiskönigin" },
  { emojis: ["🚗", "⚡", "🏁", "😎"], antwort: "Cars" },
  { emojis: ["🐼", "🥋", "🍜", "🐉"], antwort: "Kung Fu Panda 2" },
  { emojis: ["🐉", "🔥", "👑", "⚔️"], antwort: "House of the Dragon" },
  { emojis: ["👹", "🚲", "🧇", "🔦"], antwort: "Stranger Things" },
  { emojis: ["💰", "🎭", "🔴", "🇰🇷"], antwort: "Squid Game" },
  { emojis: ["👑", "💎", "👸", "🇬🇧"], antwort: "The Crown" },
  { emojis: ["🧪", "💙", "🎩", "🚐"], antwort: "Breaking Bad" },
  { emojis: ["🏝️", "✈️", "💥", "🔢"], antwort: "Lost" },
  { emojis: ["🧟", "🏹", "🔫", "🚶"], antwort: "The Walking Dead" },
  { emojis: ["🏢", "📎", "😐", "☕"], antwort: "The Office" },
  { emojis: ["☢️", "🏭", "🟡", "🍩"], antwort: "Die Simpsons" },
  { emojis: ["🕵️", "🔍", "🎻", "🇬🇧"], antwort: "Sherlock" },
  { emojis: ["🦸", "🛡️", "💥", "🌍"], antwort: "The Avengers" },
  { emojis: ["🕶️", "👽", "🔫", "🖤"], antwort: "Men in Black" },
  { emojis: ["💼", "🕶️", "🔫", "🎯"], antwort: "James Bond" },
  { emojis: ["🏴‍☠️", "⚓", "🦜", "💰"], antwort: "Fluch der Karibik" },
  { emojis: ["🚀", "🌌", "⚔️", "🤖"], antwort: "Star Wars" },
  { emojis: ["🕰️", "🚗", "⚡", "🔙"], antwort: "Zurück in die Zukunft" },
  { emojis: ["🟨", "🔵", "🧽", "🍔"], antwort: "SpongeBob" },
  { emojis: ["🍌", "👀", "🔫", "🟡"], antwort: "Ich einfach unverbesserlich" },
  { emojis: ["🐷", "🐸", "🎭", "🎬"], antwort: "Die Muppets" },
  { emojis: ["🥚", "🐲", "🏔️", "🔥"], antwort: "Drachenzähmen leicht gemacht" },
  { emojis: ["🍎", "😴", "👑", "7️⃣"], antwort: "Schneewittchen" },
  { emojis: ["👠", "🎃", "🕛", "👗"], antwort: "Cinderella" },
  { emojis: ["🦁", "🚪", "❄️", "🧙"], antwort: "Die Chroniken von Narnia" },
  { emojis: ["🍫", "🏭", "🎫", "👦"], antwort: "Charlie und die Schokoladenfabrik" },
  { emojis: ["🎣", "🐟", "🌊", "🐠"], antwort: "Der Herr der Fische" },
  { emojis: ["🦒", "🦓", "🦁", "🚢"], antwort: "Madagascar" },
  { emojis: ["👧", "🐰", "🍄", "🕳️"], antwort: "Alice im Wunderland" },
  { emojis: ["🤠", "🐴", "🌵", "🎯"], antwort: "Red Dead Redemption" },
  { emojis: ["🔵", "🌍", "🧝", "🏹"], antwort: "Avatar" },
  { emojis: ["🐗", "🦥", "🦣", "❄️"], antwort: "Ice Age" },
  { emojis: ["🥋", "🐍", "✊", "🎮"], antwort: "Mortal Kombat" },
  { emojis: ["🧱", "👷", "🟨", "🎬"], antwort: "The Lego Movie" },
  { emojis: ["🐺", "🐷", "🏠", "💨"], antwort: "Die drei kleinen Schweinchen" },
  { emojis: ["🌊", "🌺", "🛶", "🐔"], antwort: "Vaiana" },
  { emojis: ["🎈", "🏹", "🐻", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"], antwort: "Merida" },
  { emojis: ["👗", "🌹", "🕯️", "🦁"], antwort: "Die Schöne und das Biest" },
  { emojis: ["🧞", "🪔", "🐒", "🕌"], antwort: "Aladdin" },
  { emojis: ["🦌", "🌸", "🔥", "🐰"], antwort: "Bambi" },
  { emojis: ["🐕", "🍝", "🌙", "🐾"], antwort: "Susi und Strolch" },
  { emojis: ["🏴‍☠️", "👒", "🍖", "🌊"], antwort: "One Piece" },
  { emojis: ["🍜", "🦊", "🥷", "🍥"], antwort: "Naruto" },
  { emojis: ["⚡", "📓", "💀", "🍎"], antwort: "Death Note" },
  { emojis: ["🗡️", "🧱", "🏃", "👹"], antwort: "Attack on Titan" },
  { emojis: ["🔥", "🌊", "👺", "🗡️"], antwort: "Demon Slayer" },
  { emojis: ["👊", "🦸", "🥚", "💥"], antwort: "One Punch Man" },
  { emojis: ["⚗️", "🤖", "🦾", "💀"], antwort: "Fullmetal Alchemist" },
  { emojis: ["🏐", "🟠", "🐦", "🔥"], antwort: "Haikyuu" },
  { emojis: ["👊", "💚", "🦸", "🎓"], antwort: "My Hero Academia" },
  { emojis: ["🃏", "🎴", "🐉", "👑"], antwort: "Yu-Gi-Oh" },
  { emojis: ["👊", "💥", "🟡", "🐉"], antwort: "Dragon Ball" },
  { emojis: ["🍩", "😴", "👻", "⚡"], antwort: "Jujutsu Kaisen" },
  { emojis: ["🕰️", "🚪", "🔬", "🌀"], antwort: "Steins Gate" },
  { emojis: ["🎮", "⚔️", "💀", "🌐"], antwort: "Sword Art Online" },
  { emojis: ["🧪", "🔫", "🦋", "🕰️"], antwort: "Tokyo Ghoul" },
  { emojis: ["🎹", "😭", "🌸", "🎻"], antwort: "Your Lie in April" },
  { emojis: ["👣", "☄️", "🔗", "🌾"], antwort: "Your Name" },
  { emojis: ["🐷", "🏯", "👧", "👻"], antwort: "Chihiros Reise ins Zauberland" },
  { emojis: ["🐉", "🌊", "🐟", "👦"], antwort: "Ponyo" },
  { emojis: ["🐈", "🚌", "🌧️", "🌰"], antwort: "Mein Nachbar Totoro" },
  { emojis: ["🍞", "🔥", "🏰", "🧹"], antwort: "Das wandelnde Schloss" },
  { emojis: ["🐗", "🌲", "🏹", "👹"], antwort: "Prinzessin Mononoke" },
  { emojis: ["🤖", "🌆", "🧠", "🐚"], antwort: "Ghost in the Shell" },
  { emojis: ["🚴", "💊", "🏙️", "💥"], antwort: "Akira" },
  { emojis: ["🎸", "🎤", "🩸", "😈"], antwort: "Chainsaw Man" },
  { emojis: ["👨‍🍳", "🍳", "🔥", "⭐"], antwort: "Food Wars" },
  { emojis: ["🏀", "🔴", "🏫", "👟"], antwort: "Slam Dunk" },
  { emojis: ["🥊", "🥋", "💪", "🌊"], antwort: "Baki" },
  { emojis: ["🎯", "🃏", "🗼", "🐸"], antwort: "Hunter x Hunter" },
  { emojis: ["🩸", "🥩", "🐜", "🏙️"], antwort: "Parasyte" },
  { emojis: ["👹", "🗡️", "🌙", "🔔"], antwort: "Inuyasha" },
  { emojis: ["🐈", "💰", "🎩", "🌍"], antwort: "Cowboy Bebop" },
  { emojis: ["🧬", "👶", "🌊", "😢"], antwort: "Clannad" },
  { emojis: ["🍫", "😈", "🎩", "🕴️"], antwort: "Black Butler" },
  { emojis: ["🩷", "😳", "🎓", "💌"], antwort: "Kaguya-sama" }
];
